### PR TITLE
tests pass with python3.4

### PR DESCRIPTION
**Pull request by nlevitt**

### CODE REVIEW

**Comment by ikreymer** [comment]
https://github.com/ikreymer/surt/tree/py3 supports py3.2, 3.3, 3.4 ;)

**Comment by nlevitt** [comment]
Thanks! Why no pull request?!

**Comment by ikreymer** [comment]
I think I was waiting for the customization branch to be merged, looks like it has now.
I added some more customizations though, such as turning off surt mode and enabling trailing comma, but suppose can be removed:
https://github.com/internetarchive/surt/pull/8

**Comment by nlevitt** [comment]
Thanks!

**Comment by nlevitt** [comment]
Obsolete

**Pull request closed without merging**
